[2013-11-12 05:17:39,440 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid repository mirror www.toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 210, in __check_configuration_on_add
    assert mirror_hostname not in self.__repository_mirror_hostnames
AssertionError
[2013-11-12 05:17:39,442 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for bvestation.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-12 05:17:39,444 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-12 05:17:46,679 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid repository mirror www.toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 210, in __check_configuration_on_add
    assert mirror_hostname not in self.__repository_mirror_hostnames
AssertionError
[2013-11-12 05:17:46,680 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for bvestation.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-12 05:17:46,681 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-12 05:17:48,064 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid repository mirror www.toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 210, in __check_configuration_on_add
    assert mirror_hostname not in self.__repository_mirror_hostnames
AssertionError
[2013-11-12 05:17:48,064 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for bvestation.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-12 05:17:48,065 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-12 05:17:48,328 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid repository mirror www.toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 210, in __check_configuration_on_add
    assert mirror_hostname not in self.__repository_mirror_hostnames
AssertionError
[2013-11-12 05:17:48,329 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for bvestation.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-12 05:17:48,330 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-12 05:17:48,520 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid repository mirror www.toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 210, in __check_configuration_on_add
    assert mirror_hostname not in self.__repository_mirror_hostnames
AssertionError
[2013-11-12 05:17:48,521 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for bvestation.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-12 05:17:48,522 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-12 05:17:48,694 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid repository mirror www.toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 210, in __check_configuration_on_add
    assert mirror_hostname not in self.__repository_mirror_hostnames
AssertionError
[2013-11-12 05:17:48,695 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for bvestation.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-12 05:17:48,695 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-12 05:17:48,919 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid repository mirror www.toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 210, in __check_configuration_on_add
    assert mirror_hostname not in self.__repository_mirror_hostnames
AssertionError
[2013-11-12 05:17:48,920 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for bvestation.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-12 05:17:48,921 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-12 05:17:49,094 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid repository mirror www.toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 210, in __check_configuration_on_add
    assert mirror_hostname not in self.__repository_mirror_hostnames
AssertionError
[2013-11-12 05:17:49,095 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for bvestation.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-12 05:17:49,097 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-12 05:17:49,253 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid repository mirror www.toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 210, in __check_configuration_on_add
    assert mirror_hostname not in self.__repository_mirror_hostnames
AssertionError
[2013-11-12 05:17:49,254 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for bvestation.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-12 05:17:49,256 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-12 05:17:49,398 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid repository mirror www.toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 210, in __check_configuration_on_add
    assert mirror_hostname not in self.__repository_mirror_hostnames
AssertionError
[2013-11-12 05:17:49,400 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for bvestation.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-12 05:17:49,401 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-12 05:17:49,532 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid repository mirror www.toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 210, in __check_configuration_on_add
    assert mirror_hostname not in self.__repository_mirror_hostnames
AssertionError
[2013-11-12 05:17:49,534 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for bvestation.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-12 05:17:49,536 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-12 05:18:32,881 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid repository mirror www.toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 210, in __check_configuration_on_add
    assert mirror_hostname not in self.__repository_mirror_hostnames
AssertionError
[2013-11-12 05:18:32,883 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for bvestation.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-12 05:18:32,885 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-12 05:18:33,635 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid repository mirror www.toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 210, in __check_configuration_on_add
    assert mirror_hostname not in self.__repository_mirror_hostnames
AssertionError
[2013-11-12 05:18:33,637 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for bvestation.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-12 05:18:33,638 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-12 05:18:33,847 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid repository mirror www.toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 210, in __check_configuration_on_add
    assert mirror_hostname not in self.__repository_mirror_hostnames
AssertionError
[2013-11-12 05:18:33,849 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for bvestation.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-12 05:18:33,850 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-12 05:18:34,035 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid repository mirror www.toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 210, in __check_configuration_on_add
    assert mirror_hostname not in self.__repository_mirror_hostnames
AssertionError
[2013-11-12 05:18:34,037 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for bvestation.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-12 05:18:34,039 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-12 07:25:11,068 UTC] [tuf.interposition] [INFO][info:33@utility.py] Updater added for Configuration(netloc=bvestation.com:80).
[2013-11-12 07:25:11,069 UTC] [tuf.interposition] [INFO][info:33@utility.py] Found updater for hostname=bvestation.com
[2013-11-12 07:25:11,069 UTC] [tuf.interposition] [INFO][info:33@utility.py] Updater added for Configuration(netloc=bvestation.com:80).
[2013-11-12 07:25:11,070 UTC] [tuf.interposition] [INFO][info:33@utility.py] Interposing for http://bvestation.com/updates.yml
[2013-11-12 07:25:11,071 UTC] [tuf.interposition] [INFO][info:33@utility.py] Found updater for hostname=bvestation.com
[2013-11-12 07:25:11,071 UTC] [tuf.download] [INFO][download_url_to_tempfileobj:362@download.py] Downloading: http://www.toannv.com/tuf//metadata/timestamp.txt
[2013-11-12 07:25:11,072 UTC] [tuf.interposition] [INFO][info:33@utility.py] Interposing for http://bvestation.com/updates.yml
[2013-11-12 07:25:11,093 UTC] [tuf.download] [INFO][download_url_to_tempfileobj:362@download.py] Downloading: http://www.toannv.com/tuf//metadata/timestamp.txt
[2013-11-12 07:25:13,180 UTC] [tuf.download] [DEBUG][download_url_to_tempfileobj:387@download.py] Do not know how much is required to download for "http://www.toannv.com/tuf//metadata/timestamp.txt"!
[2013-11-12 07:25:13,180 UTC] [tuf.download] [DEBUG][_download_fixed_amount_of_data:285@download.py] Downloaded 942/942 bytes.
[2013-11-12 07:25:13,181 UTC] [tuf.client.updater] [WARNING][_update_metadata:694@updater.py] Bad signature on http://www.toannv.com/tuf//metadata/timestamp.txt.
[2013-11-12 07:25:13,182 UTC] [tuf.client.updater] [ERROR][_update_metadata:702@updater.py] Unable to update 'timestamp.txt'.
[2013-11-12 07:25:13,183 UTC] [tuf.download] [DEBUG][download_url_to_tempfileobj:387@download.py] Do not know how much is required to download for "http://www.toannv.com/tuf//metadata/timestamp.txt"!
[2013-11-12 07:25:13,184 UTC] [tuf.download] [DEBUG][_download_fixed_amount_of_data:285@download.py] Downloaded 942/942 bytes.
[2013-11-12 07:25:13,184 UTC] [tuf.client.updater] [WARNING][_update_metadata:694@updater.py] Bad signature on http://www.toannv.com/tuf//metadata/timestamp.txt.
[2013-11-12 07:25:13,185 UTC] [tuf.client.updater] [ERROR][_update_metadata:702@updater.py] Unable to update 'timestamp.txt'.
[2013-11-12 18:48:52,058 UTC] [tuf.interposition] [INFO][info:33@utility.py] Updater added for Configuration(netloc=tails.boum.org:80).
[2013-11-12 18:48:52,059 UTC] [tuf.interposition] [INFO][info:33@utility.py] Found updater for hostname=tails.boum.org
[2013-11-12 18:48:52,060 UTC] [tuf.interposition] [INFO][info:33@utility.py] Interposing for http://tails.boum.org/
[2013-11-12 18:48:52,061 UTC] [tuf.download] [INFO][download_url_to_tempfileobj:362@download.py] Downloading: http://www.toannv.com/tuf//metadata/timestamp.txt
[2013-11-12 18:48:54,877 UTC] [tuf.download] [DEBUG][download_url_to_tempfileobj:387@download.py] Do not know how much is required to download for "http://www.toannv.com/tuf//metadata/timestamp.txt"!
[2013-11-12 18:48:54,877 UTC] [tuf.download] [DEBUG][_download_fixed_amount_of_data:285@download.py] Downloaded 942/942 bytes.
[2013-11-12 18:48:54,878 UTC] [tuf.client.updater] [WARNING][_update_metadata:694@updater.py] Bad signature on http://www.toannv.com/tuf//metadata/timestamp.txt.
[2013-11-12 18:48:54,879 UTC] [tuf.client.updater] [ERROR][_update_metadata:702@updater.py] Unable to update 'timestamp.txt'.
[2013-11-12 18:48:55,324 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for tails.boum.org!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-12 18:48:55,324 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-12 18:49:29,961 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for tails.boum.org!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-12 18:49:29,962 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-12 18:49:32,956 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for tails.boum.org!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-12 18:49:32,956 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-12 18:50:01,769 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for tails.boum.org!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-12 18:50:01,770 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-12 18:50:30,721 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for tails.boum.org!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-12 18:50:30,721 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for tails.boum.org!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-12 18:50:30,722 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-12 18:50:30,723 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-12 18:56:47,302 UTC] [tuf.interposition] [INFO][info:33@utility.py] Updater added for Configuration(netloc=tails.boum.org:80).
[2013-11-12 18:56:47,303 UTC] [tuf.interposition] [INFO][info:33@utility.py] Updater added for Configuration(netloc=tails.boum.org:80).
[2013-11-12 18:56:47,303 UTC] [tuf.interposition] [INFO][info:33@utility.py] Found updater for hostname=tails.boum.org
[2013-11-12 18:56:47,304 UTC] [tuf.interposition] [INFO][info:33@utility.py] Found updater for hostname=tails.boum.org
[2013-11-12 18:56:47,305 UTC] [tuf.interposition] [INFO][info:33@utility.py] Interposing for https://tails.boum.org/update/v1/Tails/0.21/i386/stable/updates.yml
[2013-11-12 18:56:47,305 UTC] [tuf.interposition] [INFO][info:33@utility.py] Interposing for https://tails.boum.org/update/v1/Tails/0.21/i386/stable/updates.yml
[2013-11-12 18:56:47,306 UTC] [tuf.download] [INFO][download_url_to_tempfileobj:362@download.py] Downloading: http://www.toannv.com/tuf//metadata/timestamp.txt
[2013-11-12 18:56:47,307 UTC] [tuf.download] [INFO][download_url_to_tempfileobj:362@download.py] Downloading: http://www.toannv.com/tuf//metadata/timestamp.txt
[2013-11-12 18:56:47,484 UTC] [tuf.download] [DEBUG][download_url_to_tempfileobj:387@download.py] Do not know how much is required to download for "http://www.toannv.com/tuf//metadata/timestamp.txt"!
[2013-11-12 18:56:47,484 UTC] [tuf.download] [DEBUG][_download_fixed_amount_of_data:285@download.py] Downloaded 942/942 bytes.
[2013-11-12 18:56:47,485 UTC] [tuf.client.updater] [WARNING][_update_metadata:694@updater.py] Bad signature on http://www.toannv.com/tuf//metadata/timestamp.txt.
[2013-11-12 18:56:47,485 UTC] [tuf.client.updater] [ERROR][_update_metadata:702@updater.py] Unable to update 'timestamp.txt'.
[2013-11-12 18:56:47,495 UTC] [tuf.download] [DEBUG][download_url_to_tempfileobj:387@download.py] Do not know how much is required to download for "http://www.toannv.com/tuf//metadata/timestamp.txt"!
[2013-11-12 18:56:47,495 UTC] [tuf.download] [DEBUG][_download_fixed_amount_of_data:285@download.py] Downloaded 942/942 bytes.
[2013-11-12 18:56:47,496 UTC] [tuf.client.updater] [WARNING][_update_metadata:694@updater.py] Bad signature on http://www.toannv.com/tuf//metadata/timestamp.txt.
[2013-11-12 18:56:47,496 UTC] [tuf.client.updater] [ERROR][_update_metadata:702@updater.py] Unable to update 'timestamp.txt'.
[2013-11-12 20:44:54,259 UTC] [tuf.interposition] [INFO][info:33@utility.py] Updater added for Configuration(netloc=tails.boum.org:80).
[2013-11-12 20:44:55,023 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for tails.boum.org!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-12 20:44:55,026 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-12 20:44:56,662 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for tails.boum.org!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-12 20:44:56,662 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-12 20:45:08,985 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for tails.boum.org!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-12 20:45:08,986 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for tails.boum.org!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-12 20:45:08,986 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-12 20:45:08,987 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-12 20:45:16,184 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for tails.boum.org!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-12 20:45:16,185 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-12 20:46:46,249 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for tails.boum.org!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-12 20:46:46,250 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-12 20:47:54,544 UTC] [tuf.interposition] [INFO][info:33@utility.py] Updater added for Configuration(netloc=tails.boum.org:80).
[2013-11-12 20:47:54,545 UTC] [tuf.interposition] [INFO][info:33@utility.py] Found updater for hostname=tails.boum.org
[2013-11-12 20:47:54,545 UTC] [tuf.interposition] [INFO][info:33@utility.py] Interposing for https://tails.boum.org/update/v1/Tails/0.21/i386/stable/updates.yml
[2013-11-12 20:47:54,546 UTC] [tuf.download] [INFO][download_url_to_tempfileobj:362@download.py] Downloading: http://www.toannv.com/tuf//metadata/timestamp.txt
[2013-11-12 20:47:54,570 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for tails.boum.org!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-12 20:47:54,570 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-12 20:47:59,334 UTC] [tuf.download] [DEBUG][download_url_to_tempfileobj:387@download.py] Do not know how much is required to download for "http://www.toannv.com/tuf//metadata/timestamp.txt"!
[2013-11-12 20:47:59,334 UTC] [tuf.download] [DEBUG][_download_fixed_amount_of_data:285@download.py] Downloaded 942/942 bytes.
[2013-11-12 20:47:59,335 UTC] [tuf.client.updater] [WARNING][_update_metadata:694@updater.py] Bad signature on http://www.toannv.com/tuf//metadata/timestamp.txt.
[2013-11-12 20:47:59,336 UTC] [tuf.client.updater] [ERROR][_update_metadata:702@updater.py] Unable to update 'timestamp.txt'.
[2013-11-12 20:48:01,117 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for tails.boum.org!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-12 20:48:01,117 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-12 20:48:07,562 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for tails.boum.org!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-12 20:48:07,562 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-12 20:50:06,756 UTC] [tuf.interposition] [INFO][info:33@utility.py] Updater added for Configuration(netloc=tails.boum.org:80).
[2013-11-12 20:50:13,235 UTC] [tuf.interposition] [INFO][info:33@utility.py] Found updater for hostname=tails.boum.org
[2013-11-12 20:50:13,236 UTC] [tuf.interposition] [INFO][info:33@utility.py] Interposing for https://tails.boum.org/update/v1/Tails/0.21/i386/stable/updates.yml
[2013-11-12 20:50:13,236 UTC] [tuf.download] [INFO][download_url_to_tempfileobj:362@download.py] Downloading: http://www.toannv.com/tuf/metadata/timestamp.txt
[2013-11-12 20:50:13,326 UTC] [tuf.download] [DEBUG][download_url_to_tempfileobj:387@download.py] Do not know how much is required to download for "http://www.toannv.com/tuf/metadata/timestamp.txt"!
[2013-11-12 20:50:13,327 UTC] [tuf.download] [DEBUG][_download_fixed_amount_of_data:285@download.py] Downloaded 942/942 bytes.
[2013-11-12 20:50:13,328 UTC] [tuf.client.updater] [WARNING][_update_metadata:694@updater.py] Bad signature on http://www.toannv.com/tuf/metadata/timestamp.txt.
[2013-11-12 20:50:13,328 UTC] [tuf.client.updater] [ERROR][_update_metadata:702@updater.py] Unable to update 'timestamp.txt'.
